#DBMS 설정하기 - 개인별 DB setting 값 저장.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=shin
spring.datasource.password=tiger
